name: todart_common
description: Code shared between both the server and the application.
version: 0.1.0

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  grpc: ^3.0.2
  quiver: ^3.0.1+1
  base32: ^2.1.1